### PR TITLE
Master vx update from weblate jesuszapata

### PR DESCRIPTION
**Pull request by JesusZapata**
This PR only has the last update from the parent repository https://github.com/WeblateOrg/docker

### CODE REVIEW

**Comment by JesusZapata** [comment]
@moylop260 @ruiztulio 
In this PR only has the last change available on https://github.com/WeblateOrg/docker
Do you could accept this PR ?

**Comment by ruiztulio** [comment]
@JesusZapata We will need the [docker branch](https://github.com/WeblateOrg/docker/tree/docker) also, because they separated the repo in two branches

**Comment by JesusZapata** [comment]
@ruiztulio 
Do you could create the empty branch docker? In order to made the pull request to the docker branch.

image

This repository only has two branches `master`, `prodvx`

**Comment by JesusZapata** [comment]
This repository no has the branch `docker`

**Pull request closed without merging**
